import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import VoiceButton from "@/components/VoiceButton";
import { Toaster } from "sonner";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CartProvider>
            {children}
            <VoiceButton />
            <Toaster />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
